# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\MyProjects\芯片ID分配工具\chip_id_assignment.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_chip_id_assignment(object):
    def setupUi(self, chip_id_assignment):
        chip_id_assignment.setObjectName("chip_id_assignment")
        chip_id_assignment.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        chip_id_assignment.setFont(font)
        self.centralwidget = QtWidgets.QWidget(chip_id_assignment)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(102, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(50, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(36, 103, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_approval = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_approval.setFont(font)
        self.le_approval.setMaxLength(10000)
        self.le_approval.setObjectName("le_approval")
        self.verticalLayout.addWidget(self.le_approval)
        self.le_qty = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.le_qty.setFont(font)
        self.le_qty.setMaxLength(10000)
        self.le_qty.setObjectName("le_qty")
        self.verticalLayout.addWidget(self.le_qty)
        self.cb_type_prod = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_type_prod.setFont(font)
        self.cb_type_prod.setObjectName("cb_type_prod")
        self.cb_type_prod.addItem("")
        self.cb_type_prod.addItem("")
        self.cb_type_prod.addItem("")
        self.cb_type_prod.addItem("")
        self.cb_type_prod.addItem("")
        self.verticalLayout.addWidget(self.cb_type_prod)
        self.cb_type_id = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_type_id.setFont(font)
        self.cb_type_id.setObjectName("cb_type_id")
        self.cb_type_id.addItem("")
        self.cb_type_id.addItem("")
        self.cb_type_id.addItem("")
        self.verticalLayout.addWidget(self.cb_type_id)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(50, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(102, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(159, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.btn_assign = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_assign.setFont(font)
        self.btn_assign.setAutoDefault(False)
        self.btn_assign.setDefault(False)
        self.btn_assign.setFlat(False)
        self.btn_assign.setObjectName("btn_assign")
        self.horizontalLayout_3.addWidget(self.btn_assign)
        spacerItem6 = QtWidgets.QSpacerItem(158, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(102, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        chip_id_assignment.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(chip_id_assignment)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        chip_id_assignment.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(chip_id_assignment)
        self.statusbar.setObjectName("statusbar")
        chip_id_assignment.setStatusBar(self.statusbar)

        self.retranslateUi(chip_id_assignment)
        QtCore.QMetaObject.connectSlotsByName(chip_id_assignment)

    def retranslateUi(self, chip_id_assignment):
        _translate = QtCore.QCoreApplication.translate
        chip_id_assignment.setWindowTitle(_translate("chip_id_assignment", "芯片ID分配工具"))
        self.label.setText(_translate("chip_id_assignment", "审批单号："))
        self.label_2.setText(_translate("chip_id_assignment", "需求数量："))
        self.label_3.setText(_translate("chip_id_assignment", "产品形态："))
        self.label_4.setText(_translate("chip_id_assignment", "ID类型："))
        self.le_approval.setPlaceholderText(_translate("chip_id_assignment", "输入审批单号后6位"))
        self.le_qty.setPlaceholderText(_translate("chip_id_assignment", "输入1-99整数"))
        self.cb_type_prod.setItemText(0, _translate("chip_id_assignment", "单相表"))
        self.cb_type_prod.setItemText(1, _translate("chip_id_assignment", "三相表"))
        self.cb_type_prod.setItemText(2, _translate("chip_id_assignment", "I型采集器"))
        self.cb_type_prod.setItemText(3, _translate("chip_id_assignment", "II型采集器"))
        self.cb_type_prod.setItemText(4, _translate("chip_id_assignment", "集中器"))
        self.cb_type_id.setItemText(0, _translate("chip_id_assignment", "智芯国网送检ID"))
        self.cb_type_id.setItemText(1, _translate("chip_id_assignment", "智芯ID"))
        self.cb_type_id.setItemText(2, _translate("chip_id_assignment", "海思ID"))
        self.btn_assign.setText(_translate("chip_id_assignment", "开始分配"))
